---
microk8s_cache_valid_time: 3600
allow_world_readable_tmpfiles: true

domain: "browsertrix.cloud"

## version management
microk8s_disable_snap_autoupdate: false

microk8s_registry_size: 20Gi

microk8s_dns_servers:
  - 8.8.8.8
  - 8.8.4.4

# Define which release is installed and tracked for updates.
microk8s_channel: stable

browsertrix_cloud_home: "/opt/browsertrix-cloud"
microk8s_user: conan
microk8s_user_home: "/home/conan"
microk8s_plugins:
  dns: true              # CoreDNS
  ingress: true          # Ingress controller for external access
  helm3: true            # Helm 3 - Kubernetes package manager
  host-access: true      # Allow Pods connecting to Host services smoothly
  registry: true         # Private image registry exposed on localhost:32000
  storage: true          # Storage class; allocates storage from host
  cert-manager: true     # Cert manager
