---
# by default this playbook will add the ip address of your endpoint
# pass '-e host_name="my-domain.example.edu"' for it to work best
#
- name: deploy microk8s
  gather_facts: true
  hosts: "{{ host_ip | default('inventory_hostname') }}"
  remote_user: "{{ your_user }}"
  become: true
  vars_files:
    - ../group_vars/microk8s/main.yml
  roles:
    - "../roles/microk8s"
